import sys
from pathlib import Path

import pandas as pd
import anndata as ad

# Add project root to Python module search path
project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from scrna_workflow.multimodal_processing_and_integration import process_xenium
from scrna_workflow.graph import plot_spatial_gene_density
from scrna_workflow.downstream import report

# Configure context with resolved paths relative to the project root
input_dir = project_root / "public_data" / "xenium_breast_cancer" / "outs"
output_dir = project_root / "results" / "xenium_breast_cancer"

ctx = {
    "root": str(output_dir),
    "config": {
        "input_path": str(input_dir),
        "organism": "human",
        "biological_question": "Spatial cell state profiling in human breast cancer",
        "spatial_gene": "EPCAM"
    },
    "seed": 42
}

def run_pipeline():
    """Execute end-to-end processing, spatial graph plotting, gene visualization, and reporting."""
    # 1. Execute Xenium preprocessing & spatial graph generation
    print("Running Xenium preprocessing and spatial graph creation...")
    xenium_results = process_xenium(ctx)
    print("Xenium Process Status:", xenium_results.get("status", "completed"))

    # 2. Generate target spatial gene expression density plot (EPCAM)
    print("Generating spatial expression plot for EPCAM...")
    gene_plot_res = plot_spatial_gene_density(
        ctx, 
        dataset_path=xenium_results["outputs"]["spatial_graph"], 
        gene="EPCAM"
    )
    print("Gene plot generated at:", gene_plot_res["outputs"]["overview"])

    # 3. Build artifacts dictionary required by report()
    ctx["artifacts"] = {
        "clustering": {"outputs": {"dataset": xenium_results["outputs"]["spatial_graph"]}},
        "discovery": {"outputs": {}}
    }

    # 4. Generate downstream report and figures
    print("Generating downstream report and figures...")
    report_results = report(ctx)
    print("Report generated at:", report_results["outputs"]["report"])


def validate_xenium_outputs(results_dir):
    """Validate all dataset, image, and report artifacts generated by the pipeline."""
    results_path = Path(results_dir).resolve()
    multimodal_path = results_path / "multimodal analysis output"
    report_path = results_path / "report"
    
    # 1. Validate Processed AnnData
    h5ad_file = multimodal_path / "xenium_prepared.h5ad"
    assert h5ad_file.exists(), f"Missing dataset: {h5ad_file}"
    adata = ad.read_h5ad(h5ad_file)
    assert "spatial" in adata.obsm, "Missing spatial coordinates in obsm['spatial']"
    assert "counts" in adata.layers, "Missing raw count layer in layers['counts']"
    print(f"Dataset Verified: {adata.n_obs:,} cells x {adata.n_vars:,} genes")

    # 2. Validate Spatial Overview Figure
    overview_fig = multimodal_path / "spatial_cells_overview.png"
    assert overview_fig.exists(), f"Missing figure artifact: {overview_fig}"
    assert overview_fig.stat().st_size > 10_000, "Spatial overview figure appears corrupt or empty"
    print("Spatial overview image artifact verified.")

    # 3. Validate Spatial Gene Density Figure (EPCAM)
    gene_fig = multimodal_path / "spatial_gene_EPCAM.png"
    assert gene_fig.exists(), f"Missing gene figure artifact: {gene_fig}"
    assert gene_fig.stat().st_size > 10_000, "Spatial gene figure appears corrupt or empty"
    print("Spatial gene image artifact verified.")

    # 4. Validate Evidence Ledger inside the report folder
    ledger_file = report_path / "evidence_ledger.tsv"
    assert ledger_file.exists(), f"Missing evidence ledger TSV: {ledger_file}"
    df = pd.read_csv(ledger_file, sep="\t")
    required_cols = {"type", "finding", "artifact", "method", "confidence", "follow_up"}
    assert required_cols.issubset(df.columns), f"Ledger missing expected columns: {required_cols - set(df.columns)}"
    print(f"Evidence Ledger Verified: {len(df)} recorded findings.")


if __name__ == "__main__":
    run_pipeline()
    validate_xenium_outputs(output_dir)